documentation:
  - changed-files:
      - any-glob-to-any-file: "**/*.md"

feature:
  - head-branch: ["^feature/"]

fix:
  - head-branch: ["^fix/"]

hotfix:
  - head-branch: ["^hotfix/"]

refactor:
  - head-branch: ["^refactor/"]

release:
  - head-branch: ["^release/"]
