codecov:
  require_ci_to_pass: yes

component_management:
  default_rules:
    statuses:
      - type: project
        target: auto
        branches:
          - "!main"
  individual_components:
    - component_id: config
      name: config
      paths:
        - tools/config/**
    - component_id: logger
      name: logger
      paths:
        - tools/logger/**
    - component_id: tracer
      name: tracer
      paths:
        - tools/tracer/**

coverage:
  precision: 2
  round: down
  range: "50...75"

  status:
    project:
      default:
        target: auto
        threshold: 0%
        if_ci_failed: error
    patch:
      default:
        target: 75%

comment:
  layout: "reach, diff, flags, files, header, footer"
  behavior: default
  require_changes: false
  require_head: false
  require_base: false

ignore:
  - "tests/*"
  - "noxfile.py"
  - "**/__init__.py"
