codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "50...75"

  status:
    project:
      default:
        target: auto
        threshold: 0%
        if_ci_failed: error
    patch:
      default:
        target: 75%

comment:
  layout: "reach, diff, flags, files, header, footer"
  behavior: default
  require_changes: false
  require_head: false
  require_base: false

ignore:
  - "tests/*"
  - "noxfile.py"
  - "**/__init__.py"
