[project]
name = "default"
version = "0.1.0"
description = "This repository contains configurations to set up a Python development environment using VSCode's Dev Container feature. The environment includes uv and Ruff."

authors = [{ name = "a5chin", email = "a5chin.origin+contact@gmail.com" }]
maintainers = [{ name = "a5chin", email = "a5chin.origin+contact@gmail.com" }]

requires-python = ">=3.11"
readme = "README.md"
license = { file = "LICENSE" }

dependencies = [
    "beartype>=0.22.9",
    "google-cloud-logging>=3.15.0",
    "jaxtyping>=0.3.9",
    "pydantic>=2.13.3",
    "pydantic-settings>=2.14.0",
]

[dependency-groups]
dev = [
    "cookiecutter>=2.7.1",
    "cookiecutter-data-science>=2.3.0",
    "ipykernel>=7.2.0",
    "jupyter>=1.1.1",
    "mkdocs-material>=9.7.6",
    "nox>=2026.4.10",
    "pre-commit>=4.6.0",
    "pytest>=9.0.3",
    "pytest-cov>=7.1.0",
    "ruff>=0.15.12",
    "sqlfluff>=4.1.0",
    "ty>=0.0.33",
]

[tool.hatch.build.targets.wheel]
packages = ["tools"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
