name: Format

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ruff:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Python with uv
        uses: ./.github/actions/setup-python-with-uv

      - name: Format by Ruff
        run: uv run nox -s fmt
